### ISSUE TITLE
llama version

### ISSUE THREAD

**Issue by zhoucz97** [microsoft/LLaVA-Med#30]
What is the specific version of llama?
Llama-7b, Llama2-7b-chat-hf or Llama2-7b-chat?

**Comment by OHaiYo-lzy** [comment]
have the same confusion here

**Comment by dcampanini** [comment]
Llama-7b worked in my case

**Comment by yihp** [comment]
@dcampanini @zhoucz97 @OHaiYo-lzy Hello, did you download the pmc data set (llava_med_image_urls.jsonl) according to the author's method? My download is very slow, can you reply to me?

**Comment by dcampanini** [comment]
Hello @Kingofolk, here is the link to the llama-7b https://huggingface.co/huggyllama/llama-7b, It works for me

**Comment by fil-mp** [comment]
@dcampanini @Kingofolk @OHaiYo-lzy @zhoucz97 @yihp Hello! Does anyone have the pretrained weights from the 2 stages? It seems the authors don't provide them anymore. They only provide the v1.5 version.

Thank you for any response!
