### ISSUE TITLE
Response in messy encoding for RAD-VQA evaluation

### ISSUE THREAD

**Issue by YatingPan** [microsoft/LLaVA-Med#53]
Hi, I ran the model_vqa_med.py script on my CPU (changed .cuda() to .to('cpu) and float16 to float32, with the llama-2-7B weights applied with [data_RAD-9epoch_delta.zip](https://hanoverprod.z21.web.core.windows.net/med_llava/models/data_RAD-9epoch_delta.zip). But the response I got with CXR image is in messy encoding like:

{"question_id": "1", "prompt": "Can you describe the image for me?\n<image>", "text": "nobody \u043d\u0438schluss\uc5b4 alberga\u0435\u0433\u043e \u043a\u043e\u043c\u0438();` \u0444\u0435\u0432 everybody selects \u0444\u0435\u0432ixel", "answer_id": "chrEpZiAn2zV6XaUMbrxNP", "model_id": "/home/user/yatpan/yatpan/LLaVA-Med/llava-rad-vqa-model", "metadata": {}}

Does anyone know how to solve this? The delta weights application and inference didn't raise any errors.

**Comment by prophesierimposing** [comment]
Only llama-1 works.

**Comment by YatingPan** [comment]
> Only llama-1 works.

Thanks!
