### ISSUE TITLE
About the four delta checkpoints

### ISSUE THREAD

**Issue by MandyChaseHappy** [microsoft/LLaVA-Med#66]
Hi there.

There are four delta checkpoints under this: [https://github.com/microsoft/LLaVA-Med?tab=readme-ov-file#model-download](url). I'm not quite sure whether the base model of these four weights is llama1-7b or Vicuna-7B-v0. 

Could someone help me solve this problem?

Regards

**Comment by fil-mp** [comment]
@MandyChaseHappy Hi! Do you happen to still have these weights? I can't seem to find them anymore..

Thank you!
