### ISSUE TITLE
Applying for link to image zip

### ISSUE THREAD

**Issue by BUAADreamer** [microsoft/LLaVA-Med#71]
Thanks for your excellent job!!!
However, I found some links to the images may be unreachable or hard to access (e.g. download very slowly), I notice that in the LLaVA-Med-Peiview repo, there is an expired link to all images. Could you give a link to **the zip of all images** again? Or anyone who has downloaded all the images could give one, thanks very much!!!!!

**Comment by CinKKKyo** [comment]
我下载的时候也发现有一部分压缩包是不可用的，另外有一些图片不存在，我感觉应该就是文件名不完整

**Comment by NyKxo1** [comment]
> Thanks for your excellent job!!! However, I found some links to the images may be unreachable or hard to access (e.g. download very slowly), I notice that in the LLaVA-Med-Peiview repo, there is an expired link to all images. Could you give a link to **the zip of all images** again? Or anyone who has downloaded all the images could give one, thanks very much!!!!!

Are you getting images now? Can you share them? Thank you.

**Comment by BUAADreamer** [comment]
We release a Chinese version, you could refer to this: https://huggingface.co/datasets/BUAADreamer/llava-med-zh-instruct-60k
However, the map from the original image id to this repo can't be found.
