### ISSUE TITLE
Any plans for creating a demo website ?

### ISSUE THREAD

**Issue by PranjalSahu** [microsoft/LLaVA-Med#9]
Hello
We were trying to run the model on CXR dataset but were not able to get meaningful results.
So we wanted to check if we are using it the right way. Are there any plans that a website that gives a demo of this model will be released later ? That will help in verifying if we are using the model correctly.

Thank You

**Comment by SinanAkkoyun** [comment]
@PranjalSahu Where did you get the llava med weights from?

**Comment by PranjalSahu** [comment]
Oh I am sorry ! I meant to create this issue for for the MedFlamingo model. I am closing this issue. But still we would like to use the LLaVA-Med model as soon as possible.
